#ifndef CLIENTROOMMANAGER_GLOBAL_H
#define CLIENTROOMMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIENTROOMMANAGER_LIBRARY)
#  define CLIENTROOMMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define CLIENTROOMMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIENTROOMMANAGER_GLOBAL_H
